// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: block.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2016 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct BlockHeader {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Block number in the chain
  public var blockNum: UInt64 = 0

  /// The header_signature of the previous block that was added to the chain.
  public var previousBlockID: String = String()

  /// Public key for the component internal to the validator that
  /// signed the BlockHeader
  public var signerPublicKey: String = String()

  /// List of batch.header_signatures that match the order of batches
  /// required for the block
  public var batchIds: [String] = []

  /// Bytes that are set and verified by the consensus algorithm used to
  /// create and validate the block
  public var consensus: Data = SwiftProtobuf.Internal.emptyData

  /// The state_root_hash should match the final state_root after all
  /// transactions in the batches have been applied, otherwise the block
  /// is not valid
  public var stateRootHash: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Block {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The serialized version of the BlockHeader
  public var header: Data = SwiftProtobuf.Internal.emptyData

  /// The signature derived from signing the header
  public var headerSignature: String = String()

  /// A list of batches. The batches may contain new batches that other
  /// validators may not have received yet, or they will be all batches needed
  /// for block validation when passed to the journal
  public var batches: [Batch] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension BlockHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlockHeader"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "block_num"),
    2: .standard(proto: "previous_block_id"),
    3: .standard(proto: "signer_public_key"),
    4: .standard(proto: "batch_ids"),
    5: .same(proto: "consensus"),
    6: .standard(proto: "state_root_hash"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt64Field(value: &self.blockNum)
      case 2: try decoder.decodeSingularStringField(value: &self.previousBlockID)
      case 3: try decoder.decodeSingularStringField(value: &self.signerPublicKey)
      case 4: try decoder.decodeRepeatedStringField(value: &self.batchIds)
      case 5: try decoder.decodeSingularBytesField(value: &self.consensus)
      case 6: try decoder.decodeSingularStringField(value: &self.stateRootHash)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.blockNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.blockNum, fieldNumber: 1)
    }
    if !self.previousBlockID.isEmpty {
      try visitor.visitSingularStringField(value: self.previousBlockID, fieldNumber: 2)
    }
    if !self.signerPublicKey.isEmpty {
      try visitor.visitSingularStringField(value: self.signerPublicKey, fieldNumber: 3)
    }
    if !self.batchIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.batchIds, fieldNumber: 4)
    }
    if !self.consensus.isEmpty {
      try visitor.visitSingularBytesField(value: self.consensus, fieldNumber: 5)
    }
    if !self.stateRootHash.isEmpty {
      try visitor.visitSingularStringField(value: self.stateRootHash, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlockHeader, rhs: BlockHeader) -> Bool {
    if lhs.blockNum != rhs.blockNum {return false}
    if lhs.previousBlockID != rhs.previousBlockID {return false}
    if lhs.signerPublicKey != rhs.signerPublicKey {return false}
    if lhs.batchIds != rhs.batchIds {return false}
    if lhs.consensus != rhs.consensus {return false}
    if lhs.stateRootHash != rhs.stateRootHash {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Block: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "Block"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "header"),
    2: .standard(proto: "header_signature"),
    3: .same(proto: "batches"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBytesField(value: &self.header)
      case 2: try decoder.decodeSingularStringField(value: &self.headerSignature)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.batches)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.header.isEmpty {
      try visitor.visitSingularBytesField(value: self.header, fieldNumber: 1)
    }
    if !self.headerSignature.isEmpty {
      try visitor.visitSingularStringField(value: self.headerSignature, fieldNumber: 2)
    }
    if !self.batches.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.batches, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Block, rhs: Block) -> Bool {
    if lhs.header != rhs.header {return false}
    if lhs.headerSignature != rhs.headerSignature {return false}
    if lhs.batches != rhs.batches {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
